version: '3.8'
services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - my-redis-local:/data
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - '3000:3000'
    environment:
      REDIS_HOST: 'redis'
    depends_on:
      - redis

volumes:
  my-redis-local:
    driver: local

