version: '3.8'
services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - my-redis-local:/data
volumes:
  my-redis-local:
    driver: local
